import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseWorkbookBytes, type ParsedProperty } from "../src/lib/propertyImport";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_XLSX = resolve(
  __dirname,
  "../../../attached_assets/14___يونيو_-_Snapshot_النهائي_1782613282995.xlsx",
);
const OUT = resolve(__dirname, "../src/data/seedProperties.ts");

const bytes = new Uint8Array(readFileSync(SRC_XLSX));
const { items, sheets } = parseWorkbookBytes(bytes);

console.log("Sheets parsed:");
for (const s of sheets) console.log(`  - ${s.name}: ${s.count}`);
console.log(`Total: ${items.length}`);

const seen = new Map<string, number>();
const BASE = Date.parse("2026-06-14T12:00:00.000Z");

const records = items.map((p: ParsedProperty, i: number) => {
  let code = p.code || `ALM-${10000 + i}`;
  const n = seen.get(code) ?? 0;
  seen.set(code, n + 1);
  if (n > 0) code = `${code}-${n + 1}`;
  return {
    ...p,
    code,
    id: `seed-${i + 1}`,
    createdAt: new Date(BASE - i * 60000).toISOString(),
  };
});

const dupCodes = [...seen.entries()].filter(([, c]) => c > 1);
if (dupCodes.length) {
  console.log("Duplicate base codes (suffixed to stay unique):");
  for (const [c, n] of dupCodes) console.log(`  - ${c} x${n}`);
}

const header = `// AUTO-GENERATED by scripts/genSeed.ts — do not edit by hand.
// Source: attached_assets Excel snapshot. Re-run: pnpm --filter @workspace/alamoudi run gen:seed
import type { Property } from "@/context/DataContext";

export const SEED_PROPERTIES: Property[] = ${JSON.stringify(records, null, 2)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, header, "utf8");
console.log(`Wrote ${records.length} properties -> ${OUT}`);
